### PR TITLE
pick up value from KUBECONFIG if available

### LINKED ISSUE #149: CND does not use KUBECONFIG variable
**Describe the bug**
CND does not use the KUBECONFIG environemnt variable and always looks in the user's home folder for the configuration

**To Reproduce**
```
export KUBECONFIG=/home/pau/Desktop/cndtest/test.config
cnd up
    Activating your cloud native development environment...
    Error: stat /home/pau/.kube/config: no such file or directory
```

**Expected behavior**
CDN should read from the environment variable first

**Desktop (please complete the following information):**
 - OS: Ubuntu, Mac OS
 - All versions?

### PR DESCRIPTION
**Pull request by rberrelleza**
Fixes #149 

## Proposed changes
-  pick up value from KUBECONFIG if available, or fallback to $HOME/.kube/config

### CODE REVIEW

File: pkg/k8/client/client.go [hunk 1]
```diff
@@ -11,11 +15,27 @@ import (
...
+		}
+	}
+
+	kubeconfig := path.Join(home, ".kube", "config")
+	kubeconfigEnv := os.Getenv("KUBECONFIG")
+	if len(kubeconfigEnv) > 0 {
+		kubeconfig = kubeconfigEnv
+	}
+
+	if len(kubeconfig) == 0 {
```
Comment (pchico83) [inline pkg/k8/client/client.go]: this case is no possible, right?

Comment (rberrelleza) [reply pkg/k8/client/client.go]: yep, changing the check to see if the file exists
